---
- name: Update web servers
  become: true
  hosts: all
  remote_user: test

  tasks:
  - name: Install apache
    apt:
      name: apache2
      state: latest
    when: ansible_facts['distribution'] == "Debian" or ansible_facts['distribution'] == "Ubuntu"

  - name: Install httpd
    yum:
      name: httpd
      state: latest
    when: ansible_facts['distribution'] == "CentOS" or ansible_facts['distribution'] == "Red Hat Enterprise Linux"

  - name: restart apache
    service:
      name: apache2
      state: started
      enabled: yes
    when: ansible_facts['distribution'] == "Debian" or ansible_facts['distribution'] == "Ubuntu"

  - name: restart httpd
    service:
      name: httpd
      state: started
      enabled: yes
    when: ansible_facts['distribution'] == "CentOS" or ansible_facts['distribution'] == "Red Hat Enterprise Linux"
